let input = require('fs').readFileSync('input', 'utf8').trim().split('\n').map(x => x.split('').map(Number));

/* the code below is fully generated by Github Copilot, expect for the comment
  * and the +1 */
/* sum all the cells that have a lower value than their four neighbors */
function part1(input) {
  let sum = 0;
  for (let i = 0; i < input.length; i++) {
    for (let j = 0; j < input[i].length; j++) {
      let neighbors = [
        input[i][j - 1]+1 || +Infinity,
        input[i][j + 1]+1 || +Infinity,
        input[i - 1] ? input[i - 1][j]+1 : +Infinity,
        input[i + 1] ? input[i + 1][j]+1 : +Infinity
      ];
      if (input[i][j]+1 < Math.min(...neighbors)) {
        sum += input[i][j]+1;
      }
    }
  }
  return sum;
}

console.log(part1(input));
